service: gittron-bot-api

frameworkVersion: ">=1.1.0 <2.0.0"

package:
  exclude:
    - test/**

custom:
  myStage: ${opt:stage, self:provider.stage}
  myEnvironment:
    ORIGIN:
      prod: "https://gittron.me"
      dev: "*"
    URI_URL:
      prod: "https://data.gittron.me/v1"
      dev: "https://data.gittron.me/dev"

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  stage: dev
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
    ORIGIN: ${self:custom.myEnvironment.ORIGIN.${self:custom.myStage}}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}/index/*"

functions:
  initToken:
    handler: tokens/init-token.initToken
    events:
      - http:
          path: tokens/new
          method: post
          cors: true
  list:
    handler: tokens/list.list
    events:
      - http:
          path: tokens
          method: get
          cors: true
  getByRepo:
    handler: tokens/get-by-repo.getByRepo
    events:
      - http:
          path: tokens/repo/{ghid}
          method: get
          cors: true
  getByTokenId:
    handler: tokens/get-by-tokenid.getByTokenId
    events:
      - http:
          path: tokenid/{tokenId}
          method: get
          cors: true
  uri:
    handler: tokens/token-uri.tokenUri
    events:
      - http:
          path: uri/{tokenId}
          method: get
          cors: true
  generatePng:
    handler: tokens/generate-png.generatePng
    events:
      - http:
          path: generatepng
          method: post
          cors: true
  checkTransactionStatus:
    handler: tokens/check-transaction-status.checkTransactionStatus
    events:
      - http:
          path: tokenstatus
          method: put
          cors: true
  workerSupporter:
    handler: tokens/worker-supporter.workerSupporter
    events:
      - http:
          path: tokens/workersupporter
          method: post
          cors: true
  verifyRepo:
    handler: tokens/verify-repo.verifyRepo
    events:
      - http:
          path: verifyrepo/{tokenId}
          method: put
          cors: true
  disableToken:
    handler: tokens/disable.disable
    events:
      - http:
          path: disable/{tokenId}/{ghid}
          method: put
          cors: true

  generatePrimeBot:
    handler: bots/generate-prime-bot.generatePrimeBot
    events:
      - http:
          path: bots/new-prime
          method: post
          cors: true
  updateTxStatus:
    handler: bots/update-tx-status.updateTxStatus
    events:
      - http:
          path: bots/update-tx-status/{tokenId}
          method: put
          cors: true
  getTxStatus:
    handler: bots/get-tx-status.getTxStatus
    events:
      - http:
          path: bots/get-tx-status/{tokenId}
          method: get
          cors: true
  hatch:
    handler: bots/hatch.hatch
    events:
      - http:
          path: bots/hatch/{tokenId}
          method: put
          cors: true

resources:
  Resources:
    BotDynamoDbTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: tokenId
            AttributeType: S
          - AttributeName: ghid
            AttributeType: S
        KeySchema:
          - AttributeName: tokenId
            KeyType: HASH
          - AttributeName: ghid
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        GlobalSecondaryIndexes:
          - IndexName: byRepo
            KeySchema:
              - AttributeName: ghid
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
